In [ ]:
import pyodbc
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [ ]:
cnxn_str= ("Driver={ODBC Driver 17 for SQL Server};"
"Server=LAPTOP-96JDO3JG;"
"Database=Chinook_AutoIncrement;"
"Trusted_Connection=yes;")

In [ ]:
cnxn = pyodbc.connect(cnxn_str)

In [ ]:
cursor = cnxn.cursor()

In [ ]:
cursor.execute("Select * from dbo.dim_agent")

In [ ]:
Album = pd.read_sql("Select * from dbo.Album ", pyodbc.connect(cnxn_str))
Artist = pd.read_sql("Select * from dbo.Artist ", pyodbc.connect(cnxn_str))
Customer = pd.read_sql("Select * from dbo.Customer ", pyodbc.connect(cnxn_str))
Employee = pd.read_sql("Select * from dbo.Employee ", pyodbc.connect(cnxn_str))
Genre = pd.read_sql("Select * from dbo.Genre ", pyodbc.connect(cnxn_str))
Invoice = pd.read_sql("Select * from dbo.Invoice ", pyodbc.connect(cnxn_str))
InvoiceLine = pd.read_sql("Select * from dbo.InvoiceLine ", pyodbc.connect(cnxn_str))
MediaType = pd.read_sql("Select * from dbo.MediaType ", pyodbc.connect(cnxn_str))
Playlist = pd.read_sql("Select * from dbo.Playlist ", pyodbc.connect(cnxn_str))
PlaylistTrack = pd.read_sql("Select * from dbo.PlaylistTrack ", pyodbc.connect(cnxn_str))
Track = pd.read_sql("Select * from dbo.Track ", pyodbc.connect(cnxn_str))

In [ ]:
Album.head(10)

   AlbumId                                  Title  ArtistId
0        1  For Those About To Rock We Salute You         1
1        2                      Balls to the Wall         2
2        3                      Restless and Wild         2
3        4                      Let There Be Rock         1
4        5                               Big Ones         3
5        6                     Jagged Little Pill         4
6        7                               Facelift         5
7        8                         Warner 25 Anos         6
8        9         Plays Metallica By Four Cellos         7
9       10                             Audioslave         8

In [ ]:
Album.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 347 entries, 0 to 346
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   AlbumId   347 non-null    int64
 1   Title     347 non-null    object
 2   ArtistId  347 non-null    int64
dtypes: int64(2), object(1)
memory usage: 8.3+ KB

In [ ]:
Album['AlbumId'] = Album['AlbumId'].astype(str)
Album['ArtistId'] = Album['ArtistId'].astype(str)

In [ ]:
Album.isnull().sum()

AlbumId     0
Title       0
ArtistId    0
dtype: int64

In [ ]:
Album.duplicated().sum()

0

In [ ]:
Album['Title'].value_counts()

Title
For Those About To Rock We Salute You                 1
Lost, Season 3                                        1
Rattle And Hum                                        1
Pop                                                   1
How To Dismantle An Atomic Bomb                       1
                                                     ..
Sex Machine                                           1
Virtual XI                                            1
The X Factor                                          1
The Number of The Beast                               1
Koyaanisqatsi (Soundtrack from the Motion Picture)    1
Name: count, Length: 347, dtype: int64

In [ ]:
Artist.head(10)

   ArtistId                  Name
0         1                 AC/DC
1         2                Accept
2         3             Aerosmith
3         4     Alanis Morissette
4         5       Alice In Chains
5         6  Antônio Carlos Jobim
6         7          Apocalyptica
7         8            Audioslave
8         9              BackBeat
9        10          Billy Cobham

In [ ]:
Artist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 275 entries, 0 to 274
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ArtistId  275 non-null    int64
 1   Name      275 non-null    object
dtypes: int64(1), object(1)
memory usage: 4.4+ KB

In [ ]:
Artist['ArtistId'] = Artist['ArtistId'].astype(str)

In [ ]:
Artist.isnull().sum()

ArtistId    0
Name        0
dtype: int64

In [ ]:
Artist.duplicated().sum()

0

In [ ]:
Artist['Name'].value_counts()

Name
AC/DC                    1
Nega Gizza               1
Mundo Livre S/A          1
Los Hermanos             1
Pedro Luís E A Parede    1
                        ..
Judas Priest             1
Legião Urbana            1
Lenny Kravitz            1
Lulu Santos              1
Philip Glass Ensemble    1
Name: count, Length: 275, dtype: int64

In [ ]:
Customer.head(10)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,NaN,Theodor-Heuss-Straße 34,Stuttgart,NaN,Germany,70174,+49 0711 2842222,NaN,leonekohler@surfeu.de,5
2,3,François,Tremblay,NaN,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,NaN,ftremblay@gmail.com,3
3,4,Bjørn,Hansen,NaN,Ullevålsveien 14,Oslo,NaN,Norway,0171,+47 22 44 22 22,NaN,bjorn.hansen@yahoo.no,4
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,NaN,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4
5,6,Helena,Holý,NaN,Rilská 3174/6,Prague,NaN,Czech Republic,14300,+420 2 4177 0449,NaN,hholy@gmail.com,5
6,7,Astrid,Gruber,NaN,"Rotenturmstraße 4, 1010 Innere Stadt",Vienne,NaN,Austria,1010,+43 01 5134505,NaN,astrid.gruber@apple.at,5
7,8,Daan,Peeters,NaN,Grétrystraat 63,Brussels,NaN,Belgium,1000,+32 02 219 03 03,NaN,daan_peeters@apple.be,4
8,9,Kara,Nielsen,NaN,Sønder Boulevard 51,Copenhagen,NaN,Denmark,1720,+453 3331 9991,NaN,kara.nielsen@jubii.dk,4
9,10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4

In [ ]:
Customer['Full Name'] = Customer['FirstName'] + ' ' + Customer['LastName']
Customer.drop(['FirstName', 'LastName','Phone','State','Company','Email','PostalCode','Fax'], axis=1, inplace=True)

In [ ]:
Customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerId    59 non-null     int64
 1   Address       59 non-null     object
 2   City          59 non-null     object
 3   Country       59 non-null     object
 4   SupportRepId  59 non-null     int64
 5   Full Name     59 non-null     object
dtypes: int64(2), object(4)
memory usage: 2.9+ KB

In [ ]:
Customer['CustomerId'] = Customer['CustomerId'].astype(str)
Customer['SupportRepId'] = Customer['SupportRepId'].astype(str)

In [ ]:
Employee.head(10)

,EmployeeId,LastName,FirstName,Title,ReportsTo,BirthDate,HireDate,Address,City,State,Country,PostalCode,Phone,Fax,Email
0,1,Adams,Andrew,General Manager,NaN,1962-02-18 00:00:00.000,2002-08-14 00:00:00.000,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com
1,2,Edwards,Nancy,Sales Manager,1.0,1958-12-08 00:00:00.000,2002-05-01 00:00:00.000,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
2,3,Peacock,Jane,Sales Support Agent,2.0,1973-08-29 00:00:00.000,2002-04-01 00:00:00.000,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
3,4,Park,Margaret,Sales Support Agent,2.0,1947-09-19 00:00:00.000,2003-05-03 00:00:00.000,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
4,5,Johnson,Steve,Sales Support Agent,2.0,1965-03-03 00:00:00.000,2003-10-17 00:00:00.000,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com
5,6,Mitchell,Michael,IT Manager,1.0,1973-07-01 00:00:00.000,2003-10-17 00:00:00.000,5827 Bowness Road NW,Calgary,AB,Canada,T3B 0C5,+1 (403) 246-9887,+1 (403) 246-9899,michael@chinookcorp.com
6,7,King,Robert,IT Staff,6.0,1970-05-29 00:00:00.000,2004-01-02 00:00:00.000,590 Columbia Boulevard West,Lethbridge,AB,Canada,T1K 5N8,+1 (403) 456-9986,+1 (403) 456-8485,robert@chinookcorp.com
7,8,Callahan,Laura,IT Staff,6.0,1968-01-09 00:00:00.000,2004-03-04 00:00:00.000,923 7 ST NW,Lethbridge,AB,Canada,T1H 1Y8,+1 (403) 467-3351,+1 (403) 467-8772,laura@chinookcorp.com

In [ ]:
Employee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmployeeId  8 non-null      int64
 1   LastName    8 non-null      object
 2   FirstName   8 non-null      object
 3   Title       8 non-null      object
 4   ReportsTo   7 non-null      float64
 5   BirthDate   8 non-null      object
 6   HireDate    8 non-null      object
 7   Address     8 non-null      object
 8   City        8 non-null      object
 9   State       8 non-null      object
 10  Country     8 non-null      object
 11  PostalCode  8 non-null      object
 12  Phone       8 non-null      object
 13  Fax         8 non-null      object
 14  Email       8 non-null      object
dtypes: float64(1), int64(1), object(13)
memory usage: 1.1+ KB

In [ ]:
Employee['Full Name'] = Employee['FirstName'] + ' ' + Employee['LastName']
Employee.drop(['FirstName', 'LastName','Phone','Email','PostalCode','Fax'], axis=1, inplace=True)

In [ ]:
# Convert 'BirthDate' and 'HireDate' to datetime
Employee['BirthDate'] = pd.to_datetime(Employee['BirthDate'])
Employee['HireDate'] = pd.to_datetime(Employee['HireDate'])

# Calculate age
today = pd.Timestamp('now')
Employee['Age'] = ((today - Employee['BirthDate']) / pd.Timedelta(days=365.25)).astype(int)

# Calculate years of work
Employee['YearsOfWork'] = ((today - Employee['HireDate']) / pd.Timedelta(days=365.25)).astype(int)

# Display the updated DataFrame
Employee

,EmployeeId,Title,ReportsTo,BirthDate,HireDate,Address,City,State,Country,Full Name,Age,YearsOfWork
0,1,General Manager,NaN,1962-02-18,2002-08-14,11120 Jasper Ave NW,Edmonton,AB,Canada,Andrew Adams,62,22
1,2,Sales Manager,1.0,1958-12-08,2002-05-01,825 8 Ave SW,Calgary,AB,Canada,Nancy Edwards,65,22
2,3,Sales Support Agent,2.0,1973-08-29,2002-04-01,1111 6 Ave SW,Calgary,AB,Canada,Jane Peacock,51,22
3,4,Sales Support Agent,2.0,1947-09-19,2003-05-03,683 10 Street SW,Calgary,AB,Canada,Margaret Park,77,21
4,5,Sales Support Agent,2.0,1965-03-03,2003-10-17,7727B 41 Ave,Calgary,AB,Canada,Steve Johnson,59,20
5,6,IT Manager,1.0,1973-07-01,2003-10-17,5827 Bowness Road NW,Calgary,AB,Canada,Michael Mitchell,51,20
6,7,IT Staff,6.0,1970-05-29,2004-01-02,590 Columbia Boulevard West,Lethbridge,AB,Canada,Robert King,54,20
7,8,IT Staff,6.0,1968-01-09,2004-03-04,923 7 ST NW,Lethbridge,AB,Canada,Laura Callahan,56,20

In [ ]:
Employee = Employee.fillna(0)

In [ ]:
Employee['EmployeeId'] = Employee['EmployeeId'].astype(str)

In [ ]:
Employee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   EmployeeId   8 non-null      object
 1   Title        8 non-null      object
 2   ReportsTo    8 non-null      float64
 3   BirthDate    8 non-null      datetime64[ns]
 4   HireDate     8 non-null      datetime64[ns]
 5   Address      8 non-null      object
 6   City         8 non-null      object
 7   State        8 non-null      object
 8   Country      8 non-null      object
 9   Full Name    8 non-null      object
 10  Age          8 non-null      int64
 11  YearsOfWork  8 non-null      int64
dtypes: datetime64[ns](2), float64(1), int64(2), object(7)
memory usage: 896.0+ bytes

In [ ]:
Genre.head(10)

   GenreId                Name
0        1                Rock
1        2                Jazz
2        3               Metal
3        4  Alternative & Punk
4        5       Rock And Roll
5        6               Blues
6        7               Latin
7        8              Reggae
8        9                 Pop
9       10          Soundtrack

In [ ]:
Genre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   GenreId  25 non-null     int64
 1   Name     25 non-null     object
dtypes: int64(1), object(1)
memory usage: 528.0+ bytes

In [ ]:
Genre['GenreId'] = Genre['GenreId'].astype(str)

In [ ]:
Genre['Name'].value_counts()

Name
Rock                  1
R&B/Soul              1
Classical             1
Alternative           1
Comedy                1
Drama                 1
Sci Fi & Fantasy      1
TV Shows              1
Science Fiction       1
Hip Hop/Rap           1
World                 1
Electronica/Dance     1
Heavy Metal           1
Jazz                  1
Easy Listening        1
Bossa Nova            1
Soundtrack            1
Pop                   1
Reggae                1
Latin                 1
Blues                 1
Rock And Roll         1
Alternative & Punk    1
Metal                 1
Opera                 1
Name: count, dtype: int64

In [ ]:
Invoice.head(10)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,1,2,2021-01-01 00:00:00.000,Theodor-Heuss-Straße 34,Stuttgart,NaN,Germany,70174,1.98
1,2,4,2021-01-02 00:00:00.000,Ullevålsveien 14,Oslo,NaN,Norway,0171,3.96
2,3,8,2021-01-03 00:00:00.000,Grétrystraat 63,Brussels,NaN,Belgium,1000,5.94
3,4,14,2021-01-06 00:00:00.000,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,8.91
4,5,23,2021-01-11 00:00:00.000,69 Salem Street,Boston,MA,USA,2113,13.86
5,6,37,2021-01-19 00:00:00.000,Berger Straße 10,Frankfurt,NaN,Germany,60316,0.99
6,7,38,2021-02-01 00:00:00.000,Barbarossastraße 19,Berlin,NaN,Germany,10779,1.98
7,8,40,2021-02-01 00:00:00.000,"8, Rue Hanovre",Paris,NaN,France,75002,1.98
8,9,42,2021-02-02 00:00:00.000,"9, Place Louis Barthou",Bordeaux,NaN,France,33000,3.96
9,10,46,2021-02-03 00:00:00.000,3 Chatham Street,Dublin,Dublin,Ireland,NaN,5.94

In [ ]:
Invoice.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 412 entries, 0 to 411
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   InvoiceId          412 non-null    int64
 1   CustomerId         412 non-null    int64
 2   InvoiceDate        412 non-null    object
 3   BillingAddress     412 non-null    object
 4   BillingCity        412 non-null    object
 5   BillingState       210 non-null    object
 6   BillingCountry     412 non-null    object
 7   BillingPostalCode  384 non-null    object
 8   Total              412 non-null    float64
dtypes: float64(1), int64(2), object(6)
memory usage: 29.1+ KB

In [ ]:
Invoice['InvoiceId'] = Invoice['InvoiceId'].astype(str)
Invoice['CustomerId'] = Invoice['CustomerId'].astype(str)

In [ ]:
Invoice['BillingPostalCode'].value_counts()

BillingPostalCode
70174         7
14700         7
14300         7
M6J 1V1       7
K2P 1L7       7
R3L 2B9       7
00530         7
1720          7
01310-200     7
00192         7
00-358        7
76110         7
84102         7
1010          7
11230         7
21000         7
H-1073        7
32801         7
60611         7
12227-000     7
H2G 1A7       7
75009         7
69002         7
10012-2612    7
94040-111     7
1106          7
SW1V 3EN      7
28015         7
0171          7
89503         7
1000          7
T6G 2C7       7
2113          7
60316         7
10779         7
75002         7
33000         7
N1 5LH        7
94043-1351    7
98052-8300    7
95014         7
53703         7
85719         7
B3S 1C5       7
EH4 1HH       7
2010          7
01007-010     7
X1A 1N6       7
10789         7
1016          7
20040-020     7
71020-677     7
V6C 1G8       7
110017        7
560001        6
Name: count, dtype: int64

In [ ]:
Invoice.drop(['BillingState', 'BillingAddress','BillingPostalCode'], axis=1, inplace=True)

In [ ]:
Invoice['InvoiceDate'] = pd.to_datetime(Invoice['InvoiceDate'])

In [ ]:
Invoice

    InvoiceId CustomerId InvoiceDate BillingCity BillingCountry  Total
0           1          2  2021-01-01   Stuttgart        Germany   1.98
1           2          4  2021-01-02        Oslo         Norway   3.96
2           3          8  2021-01-03    Brussels        Belgium   5.94
3           4         14  2021-01-06    Edmonton         Canada   8.91
4           5         23  2021-01-11      Boston            USA  13.86
..        ...        ...         ...         ...            ...    ...
407       408         25  2025-12-05     Madison            USA   3.96
408       409         29  2025-12-06     Toronto         Canada   5.94
409       410         35  2025-12-09       Porto       Portugal   8.91
410       411         44  2025-12-14    Helsinki        Finland  13.86
411       412         58  2025-12-22       Delhi          India   1.99

[412 rows x 6 columns]

In [ ]:
InvoiceLine.head(10)

   InvoiceLineId  InvoiceId  TrackId  UnitPrice  Quantity
0              1          1        2       0.99         1
1              2          1        4       0.99         1
2              3          2        6       0.99         1
3              4          2        8       0.99         1
4              5          2       10       0.99         1
5              6          2       12       0.99         1
6              7          3       16       0.99         1
7              8          3       20       0.99         1
8              9          3       24       0.99         1
9             10          3       28       0.99         1

In [ ]:
InvoiceLine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   InvoiceLineId  2240 non-null   int64
 1   InvoiceId      2240 non-null   int64
 2   TrackId        2240 non-null   int64
 3   UnitPrice      2240 non-null   float64
 4   Quantity       2240 non-null   int64
dtypes: float64(1), int64(4)
memory usage: 87.6 KB

In [ ]:
InvoiceLine['InvoiceLineId'] = InvoiceLine['InvoiceLineId'].astype(str)
InvoiceLine['InvoiceId'] = InvoiceLine['InvoiceId'].astype(str)
InvoiceLine['TrackId'] = InvoiceLine['TrackId'].astype(str)

In [ ]:
InvoiceLine.describe()

         UnitPrice  Quantity
count  2240.000000    2240.0
mean      1.039554       1.0
std       0.217069       0.0
min       0.990000       1.0
25%       0.990000       1.0
50%       0.990000       1.0
75%       0.990000       1.0
max       1.990000       1.0

In [ ]:
MediaType.head(10)

   MediaTypeId                         Name
0            1              MPEG audio file
1            2     Protected AAC audio file
2            3  Protected MPEG-4 video file
3            4     Purchased AAC audio file
4            5               AAC audio file

In [ ]:
MediaType['MediaTypeId'] = MediaType['MediaTypeId'].astype(str)

In [ ]:
Playlist.head(10)

   PlaylistId          Name
0           1         Music
1           2        Movies
2           3      TV Shows
3           4    Audiobooks
4           5    90’s Music
5           6    Audiobooks
6           7        Movies
7           8         Music
8           9  Music Videos
9          10      TV Shows

In [ ]:
Playlist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   PlaylistId  18 non-null     int64
 1   Name        18 non-null     object
dtypes: int64(1), object(1)
memory usage: 416.0+ bytes

In [ ]:
Playlist['PlaylistId'] = Playlist['PlaylistId'].astype(str)

In [ ]:
PlaylistTrack.head(10)

   PlaylistId  TrackId
0           1     3402
1           1     3389
2           1     3390
3           1     3391
4           1     3392
5           1     3393
6           1     3394
7           1     3395
8           1     3396
9           1     3397

In [ ]:
PlaylistTrack['PlaylistId'] = PlaylistTrack['PlaylistId'].astype(str)
PlaylistTrack['TrackId'] = PlaylistTrack['TrackId'].astype(str)

In [ ]:
PlaylistTrack.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8715 entries, 0 to 8714
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   PlaylistId  8715 non-null   object
 1   TrackId     8715 non-null   object
dtypes: object(2)
memory usage: 136.3+ KB

In [ ]:
Playlist.duplicated().sum()

0

In [ ]:
Track.head(10)

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice
0,1,For Those About To Rock (We Salute You),1,1,1,"Angus Young, Malcolm Young, Brian Johnson",343719,11170334,0.99
1,2,Balls to the Wall,2,2,1,"U. Dirkschneider, W. Hoffmann, H. Frank, P. Ba...",342562,5510424,0.99
2,3,Fast As a Shark,3,2,1,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...",230619,3990994,0.99
3,4,Restless and Wild,3,2,1,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...",252051,4331779,0.99
4,5,Princess of the Dawn,3,2,1,Deaffy & R.A. Smith-Diesel,375418,6290521,0.99
5,6,Put The Finger On You,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",205662,6713451,0.99
6,7,Let's Get It Up,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",233926,7636561,0.99
7,8,Inject The Venom,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",210834,6852860,0.99
8,9,Snowballed,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",203102,6599424,0.99
9,10,Evil Walks,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",263497,8611245,0.99

In [ ]:
Track.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3503 entries, 0 to 3502
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   TrackId       3503 non-null   int64
 1   Name          3503 non-null   object
 2   AlbumId       3503 non-null   int64
 3   MediaTypeId   3503 non-null   int64
 4   GenreId       3503 non-null   int64
 5   Composer      2526 non-null   object
 6   Milliseconds  3503 non-null   int64
 7   Bytes         3503 non-null   int64
 8   UnitPrice     3503 non-null   float64
dtypes: float64(1), int64(6), object(2)
memory usage: 246.4+ KB

In [ ]:
Track['TrackId'] = Track['TrackId'].astype(str)
Track['AlbumId'] = Track['AlbumId'].astype(str)
Track['MediaTypeId'] = Track['MediaTypeId'].astype(str)
Track['GenreId'] = Track['GenreId'].astype(str)

In [ ]:
Track.drop(['Composer'], axis=1, inplace=True)

In [ ]:
Track['Seconds'] = (Track['Milliseconds'] / 1000).astype(int)
Track['Megabytes'] = (Track['Bytes'] / 1048576).round(2)

Track.drop(columns=['Milliseconds', 'Bytes'], inplace=True)

In [ ]:
Track

,TrackId,Name,AlbumId,MediaTypeId,GenreId,UnitPrice,Seconds,Megabytes
0,1,For Those About To Rock (We Salute You),1,1,1,0.99,343,10.65
1,2,Balls to the Wall,2,2,1,0.99,342,5.26
2,3,Fast As a Shark,3,2,1,0.99,230,3.81
3,4,Restless and Wild,3,2,1,0.99,252,4.13
4,5,Princess of the Dawn,3,2,1,0.99,375,6.00
...,...,...,...,...,...,...,...,...
3498,3499,Pini Di Roma (Pinien Von Rom) \ I Pini Della V...,343,2,24,0.99,286,4.50
3499,3500,"String Quartet No. 12 in C Minor, D. 703 ""Quar...",344,2,24,0.99,139,2.18
3500,3501,"L'orfeo, Act 3, Sinfonia (Orchestra)",345,2,24,0.99,66,1.13
3501,3502,"Quintet for Horn, Violin, 2 Violas, and Cello ...",346,2,24,0.99,221,3.50
3502,3503,Koyaanisqatsi,347,2,10,0.99,206,3.15

In [ ]:
Track.describe()

         UnitPrice      Seconds    Megabytes
count  3503.000000  3503.000000  3503.000000
mean      1.050805   393.101913    31.957779
std       0.239006   534.999876   100.510189
min       0.990000     1.000000     0.040000
25%       0.990000   207.000000     6.050000
50%       0.990000   255.000000     7.730000
75%       0.990000   321.000000     9.790000
max       1.990000  5286.000000  1010.460000

In [ ]:
Album.to_csv('Album_cleaned.csv', index=False)
Artist.to_csv('Artist_cleaned.csv', index=False)
Customer.to_csv('Customer_cleaned.csv', index=False)
Employee.to_csv('Employee_cleaned.csv', index=False)
Genre.to_csv('Genre_cleaned.csv', index=False)
Invoice.to_csv('Invoice_cleaned.csv', index=False)
InvoiceLine.to_csv('InvoiceLine_cleaned.csv', index=False)
MediaType.to_csv('MediaType_cleaned.csv', index=False)
Playlist.to_csv('Playlist_cleaned.csv', index=False)
PlaylistTrack.to_csv('PlaylistTrack_cleaned.csv', index=False)
Track.to_csv('Track_cleaned.csv', index=False)